/**
 * CREATE ENQUIRY
 */
export const ADD_ENQUIRY_CAR = "enquiry/ADD_ENQUIRY_CAR";
export const ADD_ENQUIRY_CAR_SUCCESS = "enquiry/ADD_ENQUIRY_CAR_SUCCESS";
export const ADD_ENQUIRY_CAR_ERROR = "enquiry/ADD_ENQUIRY_CAR_ERROR";

/**
 *  CREATE ENQUIRY PART HEADER
 */
export const ADD_ENQUIRY_PART_HEADER = "enquiry/ADD_ENQUIRY_PART_HEADER";
export const ADD_ENQUIRY_PART_HEADER_SUCCESS = "enquiry/ADD_ENQUIRY_PART_HEADER_SUCCESS";
export const ADD_ENQUIRY_PART_HEADER_ERROR = "enquiry/ADD_ENQUIRY_PART_HEADER_ERROR";

/**
 *  UPDATE ENNQUIRY PART HEADER
 */
 export const UPDATE_ENQUIRY_PART_HEADER = "enquiry/UPDATE_ENQUIRY_PART_HEADER";
 export const UPDATE_ENQUIRY_PART_HEADER_SUCCESS = "enquiry/UPDATE_ENQUIRY_PART_HEADER_SUCCESS";
 export const UPDATE_ENQUIRY_PART_HEADER_ERROR = "enquiry/UPDATE_ENQUIRY_PART_HEADER_ERROR";

/**
*  LOAD ENQUIRY PART HEADERS
*/
export const LOAD_ENQUIRY_PART_HEADER = "enquiry/LOAD_ENQUIRY_PART_HEADER";
export const LOAD_ENQUIRY_PART_HEADER_SUCCESS = "enquiry/LOAD_ENQUIRY_PART_HEADER_SUCCESS";
export const LOAD_ENQUIRY_PART_HEADER_ERROR = "enquiry/LOAD_ENQUIRY_PART_HEADER_ERROR";

/**
 * LOAD VEHICLE DETAILS WITH CHASSIS NUMBER
 */
export const LOAD_VEHICLE = "enquiry/LOAD_VEHICLE";
export const LOAD_VEHICLE_SUCCESS = "enquiry/LOAD_VEHICLE_SUCCESS";
export const LOAD_VEHICLE_ERROR = "enquiry/LOAD_VEHICLE_ERROR";

/**
 * LOAD MASTERS
 */
 export const LOAD_MASTER = "enquiry/LOAD_MASTER";
 export const LOAD_MASTER_SUCCESS = "enquiry/LOAD_MASTER_SUCCESS";
 export const LOAD_MASTER_ERROR = "enquiry/LOAD_MASTER_ERROR";

 /**
 *  LOAD PARTS
 */
  export const LOAD_PARTS = "enquiry/LOAD_PARTS";
  export const LOAD_PARTS_SUCCESS = "enquiry/LOAD_PARTS_SUCCESS";
  export const LOAD_PARTS_ERROR = "enquiry/LOAD_PARTS_ERROR";

/**
 *  ADD PART NUMBER
 */
   export const ADD_PART_NUMBER = "enquiry/ADD_PART_NUMBER";
   export const ADD_PART_NUMBER_SUCCESS = "enquiry/ADD_PART_NUMBER_SUCCESS";
   export const ADD_PART_NUMBER_ERROR = "enquiry/ADD_PART_NUMBER_ERROR";

/**
 * ADD PART PRICE
 */
 export const ADD_PART_PRICE = "enquiry/ADD_PART_PRICE";
 export const ADD_PART_PRICE_SUCCESS = "enquiry/ADD_PART_PRICE_SUCCESS";
 export const ADD_PART_PRICE_ERROR = "enquiry/ADD_PART_PRICE_ERROR";

/**
* LOAD PART PRICE
*/
  export const LOAD_PART_DETAILS = "enquiry/LOAD_PART_DETAILS";
  export const LOAD_PART_DETAILS_SUCCESS = "enquiry/LOAD_PART_DETAILS_SUCCESS";
  export const LOAD_PART_DETAILS_ERROR = "enquiry/LOAD_PART_DETAILS_ERROR";

/**
 * DELETE PART PRICE
 */
 export const DELETE_PART_PRICE = "enquiry/DELETE_PART_PRICE";
 export const DELETE_PART_PRICE_SUCCESS = "enquiry/DELETE_PART_PRICE_SUCCESS";
 export const DELETE_PART_PRICE_ERROR = "enquiry/DELETE_PART_PRICE_ERROR";

/**
* LOAD ENQUIRY CAR
*/
  export const LOAD_ENQUIRY_CAR_DETAILS = "enquiry/LOAD_ENQUIRY_CAR_DETAILS";
  export const LOAD_ENQUIRY_CAR_DETAILS_SUCCESS = "enquiry/LOAD_ENQUIRY_CAR_DETAILS_SUCCESS";
  export const LOAD_ENQUIRY_CAR_DETAILS_ERROR = "enquiry/LOAD_ENQUIRY_CAR_DETAILS_ERROR";

/**
 *  LOAD ENQUIRY PART DETAILS
 */
  export const LOAD_ENQUIRY_PART_DETAILS = "enquiry/LOAD_ENQUIRY_PART_DETAILS";
  export const LOAD_ENQUIRY_PART_DETAILS_SUCCESS = "enquiry/LOAD_ENQUIRY_PART_DETAILS_SUCCESS";
  export const LOAD_ENQUIRY_PART_DETAILS_ERROR = "enquiry/LOAD_ENQUIRY_PART_DETAILS_ERROR";  


  /*
  * DELETE ENQUIRY
  */
 export const DELETE_ENQUIRY = "enquiry/DELETE_ENQUIRY";
 export const DELETE_ENQUIRY_SUCCESS = "enquiry/DELETE_ENQUIRY_SUCCESS";
 export const DELETE_ENQUIRY_ERROR = "enquiry/DELETE_ENQUIRY_ERROR";


 /**
  *  UPDATE ENQUIRY VEHICLE
  */
 export const UPDATE_ENQUIRY_CAR = "enquiry/UPDATE_ENQUIRY_CAR";
 export const UPDATE_ENQUIRY_CAR_SUCCESS = "enquiry/UPDATE_ENQUIRY_CAR_SUCCESS";
 export const UPDATE_ENQUIRY_CAR_ERROR = "enquiry/UPDATE_ENQUIRY_CAR_ERROR";


